name: Deploy Glue Jobs (DEV) 

on:
  push:
    branches:
      - dev
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - uses: hashicorp/setup-terraform@v3
      
      - name: START
        run: echo "CICD Deployment in progress.."
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ secrets.AWS_REGION }}
         
      - name: Detect changed Glue scripts
        id: changes
        run: |
          git diff --name-only HEAD~1 HEAD \
            | grep '^glue-scripts/dev/' > changed_files.txt || true
          git diff --name-only HEAD~1 HEAD \
            | grep '^glue-scripts/dev/' || true > changed_files.txt
          
          if [ ! -s changed_files.txt ]; then
           echo "No changes detected — uploading ALL Glue scripts"
           find glue-scripts/dev -type f \( -name "*.py" -o -name "*.json" \) > changed_files.txt
          fi
          
          echo "Files to upload:"
          cat changed_files.txt

      - name: Detect changed Lambda functions
        id: lambda_changes
        run: |
          git diff --name-only HEAD~1 HEAD \
           | grep '^lambda/dev/' \
           | grep -v '^lambda/dev/build/' \
           | awk -F/ '{print $3}' \
           | sort -u > changed_lambdas.txt || true

          if [ ! -s changed_lambdas.txt ]; then 
            echo "No Lambda code changes detected" 
          else 
            echo "Changed Lambda functions:" 
            cat changed_lambdas.txt
          fi

      - name: Package ALL Lambda functions
        run: |
          mkdir -p lambda/dev/build
          
          cd lambda/dev/file-listener
          zip -r ../build/file-listener.zip .
          cd -

          cd lambda/dev/db-listener
          zip -r ../build/db-listener.zip .
          cd -
           
      - name: Show Lambda artifact
        run: ls -lh lambda/dev/build

      - name: Detect changed Step Functions
        id: sfn_changes
        run: |
          git diff --name-only HEAD~1 HEAD \
            | grep '^step-functions/dev/' > changed_sfns.txt || true

          if [ ! -s changed_sfns.txt ]; then
            echo "No Step Function changes detected"
          else
            echo "Changed Step Functions:"
            cat changed_sfns.txt
          fi
         
      - name: Terraform Init
        working-directory: envs/dev
        run: terraform init
              
      - name: Terraform Plan
        working-directory: envs/dev
        run: terraform plan
        
      - name: Upload Glue artifacts to S3
        run: |
         while read file; do
          echo "Uploading $file"
          aws s3 cp "$file" "s3://nagarro-glue-jobs/${file#glue-scripts/}"
         done < changed_files.txt
         
      - name: Terraform Apply
        working-directory: envs/dev
        run: terraform apply -auto-approve
        
      - name: END
        run: echo "CICD Deployment in completed!!"