name: Deploy Glue Jobs (DEV) 

on:
  push:
    branches:
      - dev
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3
      
      - name: START
        run: echo "CICD Deployment in progress.."
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ secrets.AWS_REGION }}
         
      - name: Detect changed Glue scripts
        id: changes
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} \
            | grep '^glue-scripts/dev/' || true > changed_files.txt
            
          if [ ! -s changed_files.txt ]; then
           echo "No changes detected — uploading ALL Glue scripts"
           find glue-scripts/dev -type f \( -name "*.py" -o -name "*.json" \) > changed_files.txt
          fi
          
          echo "Files to upload:"
          cat changed_files.txt
         
      - name: Terraform Init
        working-directory: envs/dev
        run: terraform init
              
      - name: Terraform Plan
        working-directory: envs/dev
        run: terraform plan
        
      - name: Upload Glue artifacts to S3
        run: |
         while read file; do
          echo "Uploading $file"
          aws s3 cp "$file" "s3://nagarro-glue-jobs/${file#glue-scripts/}"
         done < changed_files.txt

      - name: Terraform Apply
        working-directory: envs/dev
        run: terraform apply -auto-approve
        
      - name: END
        run: echo "CICD Deployment in completed!!"