name: Test Workflow 

on:
  push:
    branches:
      - dev
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3
      
      - name: START
        run: echo "CICD Deployment in progress.."
      
      - name: Detect changed Glue scripts
        id: changes
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} \
            | grep '^glue-scripts/dev/' || true > changed_files.txt

          echo "Changed files:"
          cat changed_files.txt

      - name: Terraform Init
        working-directory: envs/dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: terraform init
        
      - name: END
        run: echo "CICD Deployment in completed!!"